## Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [5]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr2 = np.array([1,2,4,6,8])

In [9]:
arr2

array([1, 2, 4, 6, 8])

In [10]:
type(arr2)

numpy.ndarray

In [11]:
my_lst_1 = [1,3,4,5]
my_lst_2 = [1,3,4,5]
my_lst_3 = [1,3,4,5]

arr = np.array([my_lst_1 ,my_lst_2 , my_lst_3])

In [12]:
arr

array([[1, 3, 4, 5],
       [1, 3, 4, 5],
       [1, 3, 4, 5]])

In [13]:
arr.shape

(3, 4)

In [14]:
arr2 = np.array([1,2,3,4,5])

In [15]:
arr2

array([1, 2, 3, 4, 5])

In [16]:
arr2[1]

2

In [18]:
arr2[1:4]

array([2, 3, 4])

In [19]:
arr

array([[1, 3, 4, 5],
       [1, 3, 4, 5],
       [1, 3, 4, 5]])

In [24]:
arr[1 , 1:4]

array([3, 4, 5])

In [20]:
arr[0:3 , 2:4]

array([[4, 5],
       [4, 5],
       [4, 5]])

In [21]:
arr[1:3 , 1:3]

array([[3, 4],
       [3, 4]])

In [22]:
arr[ , 1:5 , ]

SyntaxError: invalid syntax (2622159392.py, line 1)

In [23]:
arr[1 ,1:4]

array([3, 4, 5])

1. Create an array of 3 x 5
2. Find out the shape of an array
3. Find out 3rd element of 2nd row


In [27]:
arr_1=np.array([[4,5,6,7,8], [1,2,3,4,5], [1,3,5,7,9]])
print(np.shape(arr_1))
arr_1[1,2]

(3, 5)


3

In [26]:
print(arr_1[1,2])

3


In [28]:
arr = np.array([['1','2','3','4','5'],['1','2','3','4','5'],['1','2','3','4','5']])
print(arr)

print(arr.shape)
print(arr[2,3])

[['1' '2' '3' '4' '5']
 ['1' '2' '3' '4' '5']
 ['1' '2' '3' '4' '5']]
(3, 5)
4


In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr

array([1, 2, 3, 4, 5])

In [31]:
arr[2] = 100

In [32]:
arr

array([  1,   2, 100,   4,   5])

In [33]:
arr[2:] = 200

In [34]:
arr

array([  1,   2, 200, 200, 200])

In [35]:
arr

array([  1,   2, 200, 200, 200])

In [36]:
print(arr > 100)

[False False  True  True  True]


In [38]:
print(arr[arr > 100])

[200 200 200]


In [44]:
arr1 = np.arange(1,11)

In [45]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr1.shape

(10,)

In [50]:
arr1.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [53]:
arr = np.arange(1,11).reshape(2,5)

In [54]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [56]:
arr2 = np.arange(1,11).reshape(2,5)

In [58]:
arr * arr2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [62]:
np.ones((2,5) , dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
arr = np.random.rand(4,4)

In [70]:
arr

array([[0.229073  , 0.38028503, 0.44246461, 0.85994411],
       [0.01561534, 0.1254183 , 0.92197767, 0.39724413],
       [0.96479671, 0.76118095, 0.22807685, 0.68248221],
       [0.25852097, 0.65592186, 0.48736745, 0.06618438]])

In [68]:
import seaborn as sns

In [74]:
arr2 = np.random.randint(0,100,8).reshape(4,2)

In [75]:
arr2

array([[ 3, 42],
       [85, 69],
       [72, 23],
       [81, 25]])